#this works on Ubuntu Linux, change for your OS.
development:
  adapter:  postgresql
  encoding: utf8
  database: hackful_dev
  username: 7even
  password:
  host:     localhost

test: &test
  adapter:  postgresql
  encoding: utf8
  database: hackful_test
  username: 7even
  password:
  host:     localhost

cucumber:
  <<: *test

production:
  adapter:  postgresql
  encoding: utf8
  database: hackful_production
  username: YOUR_USERNAME # replace this with your username
  password:
  host:     localhost
